filter:
    paths: [src/*]

before_commands:
    - 'composer install --dev'

tools:
    php_cs_fixer:
        enabled: true
        config: { level: psr2 }

    php_mess_detector: true

    php_cpd:
        enabled: true

    php_analyzer:
        enabled: true

    php_pdepend:
        enabled: true

    sensiolabs_security_checker: true

    php_loc:
        enabled: true

    external_code_coverage:
        timeout: 600    # Timeout in seconds.

    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2