language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - composer self-update && composer --version
  - composer install --prefer-dist

# cache vendor dirs
cache:
  directories:
    - vendor

# faster builds on new travis setup not using sudo
sudo: false

script:
  - phpunit --coverage-clover=coverage.clover
  - php bin/limedocs generate src
