p_blondeau_user:
    resource: "@PBlondeauUserBundle/Controller/"
    type:     annotation
    prefix:   /

p_blondeau_slide_show:
    resource: "@PBlondeauSlideShowBundle/Controller/"
    type:     annotation
    prefix:   /

p_blondeau_news:
    resource: "@PBlondeauNewsBundle/Controller/"
    type:     annotation
    prefix:   /

p_blondeau_work:
    resource: "@PBlondeauWorkBundle/Controller/"
    type:     annotation
    prefix:   /

p_blondeau_exhibition:
    resource: "@PBlondeauExhibitionBundle/Controller/"
    type:     annotation
    prefix:   /

p_blondeau_press:
    resource: "@PBlondeauPressBundle/Controller/"
    type:     annotation
    prefix:   /

p_blondeau_biography:
    resource: "@PBlondeauBiographyBundle/Controller/"
    type:     annotation
    prefix:   /

p_blondeau_contact:
    resource: "@PBlondeauContactBundle/Controller/"
    type:     annotation
    prefix:   /


p_blondeau_common:
    resource: "@PBlondeauCommonBundle/Controller/"
    type:     annotation
    prefix:   /



_imagine:
    resource: .
    type:     imagine

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile