p_blondeau_news:
    resource: "@PBlondeauNewsBundle/Controller/"
    type:     annotation
    prefix:   /news

p_blondeau_work:
    resource: "@PBlondeauWorkBundle/Controller/"
    type:     annotation
    prefix:   /works

p_blondeau_exhibition:
    resource: "@PBlondeauExhibitionBundle/Controller/"
    type:     annotation
    prefix:   /exhibitions

p_blondeau_press:
    resource: "@PBlondeauPressBundle/Controller/"
    type:     annotation
    prefix:   /press

p_blondeau_biography:
    resource: "@PBlondeauBiographyBundle/Controller/"
    type:     annotation
    prefix:   /biography

p_blondeau_contact:
    resource: "@PBlondeauContactBundle/Controller/"
    type:     annotation
    prefix:   /contact


p_blondeau_common:
    resource: "@PBlondeauCommonBundle/Controller/"
    type:     annotation
    prefix:   /

